/**
 * $Id$ 
 * 
 * This file is part of the Process Language Runtime (PLR) 
 * and is licensed under the GPL v3.0.
 * 
 * Author: Einar Egilsson (einar@einaregilsson.com) 
 */
 ﻿using System;
using System.Collections.Generic;
using System.Reflection.Emit;
using System.Reflection;
using PLR.Compilation;

namespace PLR.AST.Expressions {
    public class Variable : Expression {
        protected string _name;
        private LocalBuilder _local;
        private static int _genCounter = 0;
        public string Name { get { return _name; } }
        public Variable(string name) {
            _name = name;
        }
        public Variable(LocalBuilder local) {
            _name = "AutoGenerated" + _genCounter++;
            _local = local;
        }

        public override bool Equals(object obj) {
            if (!(obj is Variable)) return false;

            return this.Name == ((Variable)obj).Name;
        }
        public override int GetHashCode() {
            return this.Name.GetHashCode();
        }
        public override void Accept(AbstractVisitor visitor) {
            visitor.Visit(this);
            base.Accept(visitor);
        }
        public override Type Type {
            get {
                if (_local != null) {
                    return _local.LocalType;
                } else {
                    return typeof(object);
                }
            }
        }

        #region Compilation
        public virtual void Declare(ILGenerator il) {
            if (_local != null) {
                throw new InvalidOperationException("Variable " + _name + " is already declared!");
            }
            _local = il.DeclareLocal(this.Type);
            _local.SetLocalSymInfo(_name);
        }

        public virtual void AssignTo(ILGenerator il) {
            il.Emit(OpCodes.Stloc, _local);
        }

        public override string ToString() {
            return _name;
        }

        public override void Compile(CompileContext context) {
            if (_local != null) {
                context.ILGenerator.Emit(OpCodes.Ldloc, _local);
            } else {
                LocalBuilder local = context.Type.GetLocal(_name);
                if (local == null) {
                    local = context.ILGenerator.DeclareLocal(typeof(object));
                    if (context.Options.Debug) {
                        local.SetLocalSymInfo(_name);
                    }
                    context.Type.Locals.Add(_name, local);
                }
                context.ILGenerator.Emit(OpCodes.Ldloc, local);

            }
        }
        #endregion
    }
}
